#!/usr/bin/env bash
# @AUTHOR: Chun-Jie Liu
# @CONTACT: chunjie.sam.liu.at.gmail.com
# @DATE: 2020-05-17 10:46:50
# @DESCRIPTION:

# Number of input parameters
param=$1

find ${HOME}/github/autophagy-in-cancer \
    ${HOME}/github/TEP-OV \
    ${HOME}/github/EVAtlas-analysis \
    ${HOME}/github/Deeplatelet \
    ${HOME}/github/learning-codes \
    -type f \
    -name '*R' | xargs grep -i ${param}