#!/usr/bin/env bash


ci=`docker ps|grep Jrocker|cut -f 1 -d ' '`

function runExec {
  if [ -z ${ci} ]
  then
    echo "Error: No Jrocker Running."
    exit 0
  else 
    echo "Notice: Exec Jrocker Container: ${ci}."
    cmd="docker exec -it -u liucj:root ${ci} bash"
    eval ${cmd}
  fi
}

runExec