#!/usr/bin/env bash

param=$#
serv=$1
variable=$2

arr[1]='login'
arr[2]='compute'
arr[3]='dn'
arr[4]='ss'

function usage {
  if [ "$param" -gt 2 -o "${param}" -lt 1 ]
	then
		echo "Usage:"
		echo "	hpc-login [jrocker|jukeras]"
		echo "Details:"
		echo "	login -> connect hpc login node."
		echo "	compute -> connect hpc compute node."
    echo "	ss -> show process."
    echo "	dn -> shutdown process."
		echo "For example:"
		echo "	hpc-login jrocker"
		exit 1
	fi
  if [[ ! "${arr[@]}" =~ "$serv" ]]
	then
		echo "Error:"
		echo "	Input must be one of 'jrocker', 'jukeras', 'ss', 'dn' to start jrocker"
		echo "Example:"
		echo "	hpc-login jrocker"
		exit 1
	fi
}
function login {
  cmd="sshpass -p 'password' ssh -p port -N -f -L localhost:10000:localhost:10000 username@ip"
  eval ${cmd}
}
function compute {
  cmd="sshpass -p 'password' ssh -p port -N -f -L localhost:10001:b01:10000 username@ip"
  eval ${cmd}
}
function dn {
  ps aux|grep 'ssh -p port -N -f -L localhost'|grep -v grep|awk '{print $2}'|xargs kill
}
function ss {
  ps aux|grep 'ssh -p port -N -f -L localhost'|grep -v grep
}

usage
[[ ${serv} = 'login' ]] && login || usage
[[ ${serv} = 'compute' ]] && compute || usage
[[ ${serv} = 'dn' ]] && dn || usage
[[ ${serv} = 'ss' ]] && ss || usage