#!/usr/bin/env bash
# @AUTHOR: Chun-Jie Liu
# @CONTACT: chunjie.sam.liu.at.gmail.com
# @DATE: 2019-07-12 21:21:53
# @DESCRIPTION:


# imgs=(python:2.7 ubuntu:16.04 broadinstitute/gatk:4.0.10.0 broadinstitute/gatk:4.0.8.1 ensemblorg/ensembl-vep:release_94.5 broadinstitute/genomes-in-the-cloud:2.3.1-1512499786 broadinstitute/oncotator:1.9.9.0)
imgs=(chunjiesamliu/jrocker:latest)

for img in ${imgs[@]};
do
  tar_name=`echo ${img}|sed -e 's/\//_/'`
  cmd="nohup docker save --output ${tar_name}.tar ${img} > ${tar_name}.nohup.out 2>&1 &"
  # echo ${cmd}
  eval ${cmd}
done
